name: blink_comparison
description: Simplifies comparing photos of tamper-evident seals and patterns using your eyes.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+5

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  auto_route: ^3.2.1
  bloc: ^8.0.2
  camera: ^0.9.4+16
  cross_file: ^0.3.1+5
  cupertino_icons: ^1.0.2
  devicelocale: ^0.5.0
  device_info_plus: ^3.0.1
  equatable: ^2.0.3
  extended_image: ^6.0.1
  file: ^6.1.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  flutter_bloc: ^8.0.1
  flutter_colorpicker: ^1.0.2
  flutter_image_compress: ^1.1.0
  flutter_linkify: ^5.0.2
  flutter_mailer: ^2.0.0
  flutter_sodium:
    git:
      url: https://github.com/proninyaroslav/flutter_sodium.git
      ref: linux
  flutter_local_notifications: ^9.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_staggered_grid_view: ^0.6.1
  freezed_annotation: ^1.0.0
  image_picker: ^0.8.4
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  json_serializable: ^6.0.0
  just_audio: ^0.9.16
  logger: ^1.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  package_info_plus: ^1.0.6
  path_provider: ^2.0.2
  path_provider_android: ^2.0.12
  path_provider_ios: ^2.0.8
  path: ^1.8.0
  quiver: ^3.0.1
  responsive_builder: ^0.4.1
  sembast_sqflite: ^2.0.0+1
  sembast: ^3.1.0+2
  shared_preferences: ^2.0.8
  shared_preferences_android: ^2.0.11
  shared_preferences_ios: ^2.1.0
  showcaseview: ^1.1.4
  sqflite_common_ffi: ^2.0.0+3
  sqflite: ^2.0.0+4
  swipe:
    git:
      url: https://github.com/proninyaroslav/swipe.git
      ref: patch-1
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  wakelock: ^0.6.1+1

dev_dependencies:
  analyzer: ^3.2.0
  auto_route_generator: ^3.2.1
  bloc_test: ^9.0.2
  build_runner: ^2.1.1
  device_preview: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  intl_utils: ^2.6.0
  mocktail: ^0.3.0

dependency_overrides:
  analyzer: ^3.2.0
  # TODO: remove after merge a PR https://github.com/magnatronus/flutter-devicelocale/pull/40
  devicelocale:
    git:
      url: https://github.com/proninyaroslav/flutter-devicelocale.git
      ref: android-ietf-tags

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/audio/camera_shutter.mp3
    - assets/app_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
